### ISSUE TITLE
Lambda function source code does not work with Node 4.3

### ISSUE THREAD

**Issue by phuson** [awslabs/amz-ai-building-better-bots#5]
It looks like the last change to the lambda function source code (https://github.com/awslabs/amz-ai-building-better-bots/commit/bd472371b2f3ede539492923d8e8ab83cf12ef61) only works with Node 6.10, not 4.3. If this is true, please update the README.md file (https://github.com/awslabs/amz-ai-building-better-bots/blob/master/README.md#lambda-function) to prevent confusion. Thanks!

**Comment by nhira** [comment]
Thanks for calling this out.  Fixed.
